### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by kiozix** [deStrO/eBot-CSGO-Web#107]
hello i create ebot on vm on ubuntu is work but web panel send 404 not found

i try ebotlink.link/ebot/matchs/view/2 not work
and ebotlink.link/ebot/index.php/matchs/view/2 work but all link not use index.php

root@Ebot:~# a2enmod rewrite
Module rewrite already enabled
on web show
https://prnt.sc/rqvpzr

whit index.php befor link
https://prnt.sc/rqvqsr

any help for this please

**Comment by MikkelDK** [comment]
screenshot .htaccess =)

**Comment by kiozix** [comment]
the .htaccess empty ^^

**Comment by MikkelDK** [comment]
> the .htaccess empty ^^

No! @kiozix - it's under "web" folder =)

**Comment by kiozix** [comment]
yes on /web/.htaccess is empty

**Comment by kiozix** [comment]
![image](https://user-images.githubusercontent.com/31328799/78148283-fb369080-7434-11ea-86cd-057e81484425.png)
![image](https://user-images.githubusercontent.com/31328799/78148313-038ecb80-7435-11ea-9840-75832daf0105.png)
i follow your guide but not working
