### ISSUE TITLE
Missing force end warmup in OT

### ISSUE THREAD

**Issue by Iwhite67** [deStrO/eBot-CSGO-Web#114]
https://github.com/deStrO/eBot-CSGO-Web/blob/60d79fd1081b72bd49b922c1a3484ac77b25f3fd/apps/backend/modules/matchs/actions/actions.class.php#L789C125-L789C125

Missing 
STATUS_WU_OT_1_SIDE
STATUS_WU_OT_2_SIDE

new line : 
`                } else if ($match->getStatus() == Matchs::STATUS_WU_1_SIDE || $match->getStatus() == Matchs::STATUS_WU_2_SIDE || $match->getStatus() == Matchs::STATUS_WU_OT_1_SIDE || $match->getStatus() == Matchs::STATUS_WU_OT_2_SIDE ) {`

**Comment by deStrO** [comment]
Fixed, thanks @Iwhite67 !
