### ISSUE TITLE
Missing weapon image knife_butterfly.png

### ISSUE THREAD

**Issue by ml-** [deStrO/eBot-CSGO-Web#42]
**/images/kills/csgo/knife_butterfly.png** missing.

Example not really required but whatever:
http://live.csgo-emsone.com/stats/players/STEAM_1%3A0%3A8789638

**Comment by Moondarker** [comment]
Check out my fork, i did some changes in images for kill logs.
https://github.com/Moondarker/eBot-CSGO-Web
