### ISSUE TITLE
Unable to parse error

### ISSUE THREAD

**Issue by dlwh13** [deStrO/eBot-CSGO-Web#48]
I try to make private eBot server, but I have problem
I type command 'php symfony cc', but it print this error
"Unable to parse file "/usr/share/ebot/config/app.yml": Unable to parse line 21 (  .array:)."
I don't know why symfony print this error, I try to edited app.yml, but I didn't solve this problem
anyone solved this problem?
(Sorry for my bad english)

and is eBot still continue the project?

**Comment by dlwh13** [comment]
my mistake, sorry

**Comment by MrPalamen** [comment]
c'est ou

**Comment by baster33** [comment]
@dlwh13 What was Your problem reason? I encountered it today, maybe You can help me?

**Comment by baster33** [comment]
I got it. In case anybody else will face it, the reason was bad indent in app_user.yml (i copy-pasted code from installation process, which had no spaces at beginning).
