### ISSUE TITLE
symfony: app.yml has syntax problem. Need fix!

### ISSUE THREAD

**Issue by MTRNord** [deStrO/eBot-CSGO-Web#49]
My symfony won't parse the "config/app.yml" file. It says: 'Unable to parse file "/var/www/eBot-CSGO-Web/config/app.yml": Unable to parse line 7 ( all:).' when running "php symfony cc". If I am right it is because of the php code in it. Can any one aprove this or/and fix it?

In apache2 the error looks like: '[Wed Dec 16 19:00:08 2015] [error] [client x.x.x.x] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Unable to parse file "/var/www/eBot-CSGO-Web/config/app.yml": Unable to parse line 17 (  .array:).' in /var/www/eBot-CSGO-Web/lib/vendor/symfony/lib/yaml/sfYaml.php:100\nStack trace:\n#0 /var/www/eBot-CSGO-Web/lib/vendor/symfony/lib/config/sfYamlConfigHandler.class.php(72): sfYaml::load('/var/www/eBot-C...')\n#1 /var/www/eBot-CSGO-Web/lib/vendor/symfony/lib/config/sfYamlConfigHandler.class.php(39): sfYamlConfigHandler::parseYaml('/var/www/eBot-C...')\n#2 /var/www/eBot-CSGO-Web/lib/vendor/symfony/lib/config/sfDefineEnvironmentConfigHandler.class.php(146): sfYamlConfigHandler::parseYamls(Array)\n#3 /var/www/eBot-CSGO-Web/lib/vendor/symfony/lib/config/sfDefineEnvironmentConfigHandler.class.php(45): sfDefineEnvironmentConfigHandler::getConfiguration(Array)\n#4 /var/www/eBot-CSGO-Web/lib/vendor/symfony/lib/config/sfConfigCache.class.php(108): sfDefineEnvironmentConfigHandler->execute(Array)\n#5 /var/www/eBot-CSGO-Web/lib/vendor/symfony/lib/config/sfConfigCache.c in /var/www/eBot-CSGO-Web/lib/vendor/symfony/lib/yaml/sfYaml.php on line 100'

**Comment by mavrick** [comment]
Run this again inside the csgo-web folder

``cp config/app_user.yml.default config/app_user.yml``

the app_user.yml is probably corrupt. 

```
# ----------------------------------------------------------------------
# white space are VERY important, don't remove it or it will not work
# ----------------------------------------------------------------------
```

Make sure there is white space at the start of each line

```
  log_match: ../../ebotv3/logs/log_match
  log_match_admin: ../../ebotv3/logs/log_match_admin
  demo_path: ../../ebotv3/demos
```

Let me know how you go
