### ISSUE TITLE
Just Web

### ISSUE THREAD

**Issue by isayldz** [deStrO/eBot-CSGO-Web#50]
Hello i want use just ebot web. i using splewish pug for 5vs5 matchs but how i will install ebot web for my gameserver ?  the install info not enough there is another easy way ? or video ? i using linux centos 6

and 1 morething on my dedicated i have more than 1 server how i will use for all ebot web ? thanks.

**Comment by excalibur3000** [comment]
Hello,
i am trying that too. My bot ist just working, but the web panel isn't. Perhaps we can make it together.

Best regards
Christian
