### ISSUE TITLE
Do you guys have a SQL-string, which creates the whole database? Or where can I find it?

### ISSUE THREAD

**Issue by Leducia** [deStrO/eBot-CSGO-Web#52]
I don't want the admin panel which comes with eBot, I'm going to create a whole other system. Anyways, I need the database structure needed for eBot to work, but I dont feel like installing the admin panel, just to get this. 

Bottom line: Do you have a SQL string I can run in my phpmyadmin?

Best regards, Per Hansen

**Comment by iTsFILIPOficial** [comment]
@Leducia The database files are here: https://github.com/deStrO/eBot-CSGO-Web/tree/master/data
You may be able to use them.
