### ISSUE TITLE
admin.php is white/dns error (app.yml)

### ISSUE THREAD

**Issue by MikkelDK** [deStrO/eBot-CSGO-Web#64]
Hello,

i got problem with app.yml

error:
Uncaught exception 'InvalidArgumentException' with message 'Unable to parse file "/var/www/eBot-WEB/config/app.yml": Unable to parse line 21 (  .array:).'

what to do?

**Comment by mgjuhler** [comment]
you've most likely been fixed in the car and with made a mistake which makes the file is not correct. (Have you added a new map?)

**Comment by MikkelDK** [comment]
Yeah, it was the problem hehe. :-)
