### ISSUE TITLE
eBot User permission

### ISSUE THREAD

**Issue by MikkelDK** [deStrO/eBot-CSGO-Web#65]
Hello,

How can i install the user permission on the eBot version?

if i register one user, the user has "automatic" fully admin. and delete my account etc etc.

What to do?

**Comment by AldemaroC** [comment]
I want know too. Is there any place where I can set user permissions?

**Comment by MikkelDK** [comment]
it's not possible! :)

**Comment by MikkelDK** [comment]
@deStrO - Are it' possible for getting update about this, about it's required for pay or something. - thanks.
