### ISSUE TITLE
Local installation tutorial

### ISSUE THREAD

**Issue by Tralala0000** [deStrO/eBot-CSGO-Web#66]
Hi. Can someone make video how to install and setup ebot on my local computer with windows OS from the scratch. Im new at web so i try to install wamp and composer and node js but nothing happend :/

**Comment by MARVIN1994PL** [comment]
[](https://github.com/deStrO/eBot-CSGO-Web/wiki)

**Comment by digitalfarseer** [comment]
I can help you with installation, skype: digitalfarseer.
