### ISSUE TITLE
m.tv_record_file

### ISSUE THREAD

**Issue by KowalskyZBL** [deStrO/eBot-CSGO-Web#67]
When I create match and I want to go to Matches in Progress I have a error: Page could not be loaded due to an error.

In apache log: [Sat May 07 17:26:33.898884 2016] [:error] [pid 12474] [client XXXXXXXX:63077] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'm.tv_record_file' in 'field list', referer: http://XXXXXX/admin.php/matchs/create

**Comment by oleghalin** [comment]
i have same error.

**Comment by KowalskyZBL** [comment]
oleghalin, install the database with php symfony

Insert the database:

php symfony doctrine:insert-sql

Create a admin user profile:

php symfony guard:create-user --is-super-admin admin@ebot admin password
