### ISSUE TITLE
Enable registration for new users

### ISSUE THREAD

**Issue by chris100184** [deStrO/eBot-CSGO-Web#70]
Currently got the web panel installed on my website, but i can't seem to find anywhere to allow users to sign up for an account, so they can access the panel. Is there some option to enable this feature?

**Comment by Versatile-BFG** [comment]
not with the released web code. This is only for private use.

**Comment by chris100184** [comment]
Damn, i guess you could have data transfer from i.e a wordpress database, so when people sign up via wordpress, the credentials will also be added to the ebot database.
