### ISSUE TITLE
Undefined index: WORKSHOP (Centos 6.7)

### ISSUE THREAD

**Issue by theatec900** [deStrO/eBot-CSGO-Web#71]
I got message ( PHP Notice:  Undefined index: WORKSHOP in /tmp/eBot/src/eBot/Config/Config.php on line 68 ) 
when I started a bot like this pic below. 

![capture](https://cloud.githubusercontent.com/assets/3788884/15991448/4cdaa1d2-30dd-11e6-9e00-924744962e70.JPG)

and I used a public ip for ebot, I have tried to run a bot it can send rcon command to csgo server but cant received any messages from csgo server. 
PS. csgo server I rent from clanwarz.com.

**Comment by MikkelDK** [comment]
Just ignore WORKSHOP :)

I dont think someone is using workshop map (example dust2_se)
