### ISSUE TITLE
Demo button away

### ISSUE THREAD

**Issue by MikkelDK** [deStrO/eBot-CSGO-Web#73]
Hey,

i running the privately ebot.

Where demo/download is true (enabled)

But it's away.
(Screenshot):
![ebot1](https://cloud.githubusercontent.com/assets/5301047/16306811/430db75e-395f-11e6-8221-7ac7cde8a6ec.png)
![ebot2](https://cloud.githubusercontent.com/assets/5301047/16306816/473807f8-395f-11e6-8c73-615e0b84c49c.png)

But no "demos" :(

**Comment by Famous030** [comment]
Same for me all other Works but i can't find that Demo button...

The demos all correctly in - /home/ebot/ebot-csgo/demos

maybe some help plz
