### ISSUE TITLE
Add a workshop map

### ISSUE THREAD

**Issue by Gicminos** [deStrO/eBot-CSGO-Web#83]
The wiki explain how to add a new map
https://github.com/deStrO/eBot-CSGO-Web/wiki/Add-maps-to-map-pool

modifying this
https://github.com/deStrO/eBot-CSGO-Web/blob/master/config/app.yml

But how can I add a workshop map??

Thank you.

**Comment by MikkelDK** [comment]
Example:
maps: [ de_dust2, de_nuke, de_inferno, de_train, de_mirage, de_season, de_cache, de_overpass, de_cbble, de_tuscan  workshop/XXXXXX/de_dust2_se]

What i think is possible.

**Comment by Gicminos** [comment]
The URL for de_dust2_se is http://steamcommunity.com/sharedfiles/filedetails/?id=125488374

the correct form is
maps: [ de_dust2, de_nuke, de_inferno, de_train, de_mirage, de_season, de_cache, de_overpass, de_cbble, de_tuscan, workshop/125488374/de_dust2_se]

or at "XXXXXX" I need to put the collection?

**Comment by MikkelDK** [comment]
correct form is:

maps: [ de_dust2, de_nuke, de_inferno, de_train, de_mirage, de_season, de_cache, de_overpass, de_cbble, de_tuscan, workshop/125488374/de_dust2_se ]

**Comment by MikkelDK** [comment]
I thinking you need too to edit here:

https://github.com/deStrO/eBot-CSGO/blob/master/config/config.ini.smp <<
