### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by RaitoBezarius** [deStrO/eBot-CSGO-Web#84]
Is this project free, under some kind of license?

Please, if this project is OSS software, [choose a license!](http://choosealicense.com/)

**Comment by Versatile-BFG** [comment]
License

The code is under Creative Commons license. You can find all details here: http://creativecommons.org/licenses/by/3.0/

You can copy, distribute, modify the source code, but you have to keep the license terms.

**Comment by Versatile-BFG** [comment]
It's in the readme file.

**Comment by RaitoBezarius** [comment]
@Versatile-BFG Right, thanks!
