### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by MarkusKoo** [deStrO/eBot-CSGO-Web#85]
Hi,

Database creation on installation fails with error   

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes. Failing Query: "CREATE TABLE sf_guard_user (id BIGINT AUTO_INCREMENT, first_name VARCHAR(255), last_name VARCHAR(255), email_address VARCHAR(255) NOT NULL UNIQUE, username VARCHAR(128) NOT NULL UNIQUE, algorithm VARCHAR(128) DEFAULT 'sha1' NOT NULL, salt VARCHAR(128), password VARCHAR(128), is_active TINYINT(1) DEFAULT '1', is_super_admin TINYINT(1) DEFAULT '0', last_login DATETIME, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX is_active_idx_idx (is_active), PRIMARY KEY(id)) ENGINE = INNODB". Failing Query: CREATE TABLE sf_guard_user (id BIGINT AUTO_INCREMENT, first_name VARCHAR(255), last_name VARCHAR(255), email_address VARCHAR(255) NOT NULL UNIQUE, username VARCHAR(128) NOT NULL UNIQUE, algorithm VARCHAR(128) DEFAULT 'sha1' NOT NULL, salt VARCHAR(128), password VARCHAR(128), is_active TINYINT(1) DEFAULT '1', is_super_admin TINYINT(1) DEFAULT '0', last_login DATETIME, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX is_active_idx_idx (is_active), PRIMARY KEY(id)) ENGINE = INNODB  
                                                                                                                                                                      Any tips?

**Comment by MikkelDK** [comment]
I will recommend you using forum! :) >> forum.esport-tools.net

**Comment by eclipse95** [comment]
Hi @MarkusKoo ,
I had the same issue when I used PHP7. PHP7 isn't supported yet.
Try to use PHP5, it fixes my problem.

**Comment by FromeXo** [comment]
The problem here is that INNODB utf8 max varchar is VARCHAR(255) and  INNODB utf8mb4 VARCHAR(191) so to solve this i located the sql in ebot-web/data/sql/schema.sql
Copyed all that in to my fav codeing editor and replaced all VARCHAR(255) with VARCHAR(191) and run the sql right in to my mysql console then i could just run php symfony guard:create-user --is-super-admin admin@ebot admin admin from ebot-web/ and continue as normal
