### ISSUE TITLE
Any links on the index give an error 500

### ISSUE THREAD

**Issue by dumle29** [deStrO/eBot-CSGO-Web#86]
So the admin panel works, but the links like stats, language switching, credits, etc, all break with an error 500.

This is the apache error log with LogLevel debug:

`[Sun Feb 05 23:43:24.640879 2017] [authz_core:debug] [pid 3318] mod_authz_core.c(802): [client my.ho.me.ip:port] AH01626: authorization result of Require all granted: granted, referer: http://my.ser.ver.ip/
[Sun Feb 05 23:43:24.641536 2017] [authz_core:debug] [pid 3318] mod_authz_core.c(802): [client my.ho.me.ip:port] AH01626: authorization result of <RequireAny>: granted, referer: http://my.ser.ver.ip/
[Sun Feb 05 23:43:24.643407 2017] [core:error] [pid 3318] [client my.ho.me.ip:port] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://my.ser.ver.ip/
[Sun Feb 05 23:43:24.643694 2017] [core:debug] [pid 3318] core.c(3518): [client my.ho.me.ip:port] AH00121: r->uri = /home/ebot/ebot-web/web/index.php, referer: http://my.ser.ver.ip/
[Sun Feb 05 23:43:24.643856 2017] [core:debug] [pid 3318] core.c(3525): [client my.ho.me.ip:port] AH00122: redirected from r->uri = /home/ebot/ebot-web/web/index.php, referer: http://my.ser.ver.ip/
[Sun Feb 05 23:43:24.644115 2017] [core:debug] [pid 3318] core.c(3525): [client my.ho.me.ip:port] AH00122: redirected from r->uri = /home/ebot/ebot-web/web/index.php, referer: http://my.ser.ver.ip/
[Sun Feb 05 23:43:24.644277 2017] [core:debug] [pid 3318] core.c(3525): [client my.ho.me.ip:port] AH00122: redirected from r->uri = /home/ebot/ebot-web/web/index.php, referer: http://my.ser.ver.ip/
[Sun Feb 05 23:43:24.644435 2017] [core:debug] [pid 3318] core.c(3525): [client my.ho.me.ip:port] AH00122: redirected from r->uri = /home/ebot/ebot-web/web/index.php, referer: http://my.ser.ver.ip/
[Sun Feb 05 23:43:24.644653 2017] [core:debug] [pid 3318] core.c(3525): [client my.ho.me.ip:port] AH00122: redirected from r->uri = /home/ebot/ebot-web/web/index.php, referer: http://my.ser.ver.ip/
[Sun Feb 05 23:43:24.644814 2017] [core:debug] [pid 3318] core.c(3525): [client my.ho.me.ip:port] AH00122: redirected from r->uri = /home/ebot/ebot-web/web/index.php, referer: http://my.ser.ver.ip/
[Sun Feb 05 23:43:24.644970 2017] [core:debug] [pid 3318] core.c(3525): [client my.ho.me.ip:port] AH00122: redirected from r->uri = /home/ebot/ebot-web/web/index.php, referer: http://my.ser.ver.ip/
[Sun Feb 05 23:43:24.645119 2017] [core:debug] [pid 3318] core.c(3525): [client my.ho.me.ip:port] AH00122: redirected from r->uri = /home/ebot/ebot-web/web/index.php, referer: http://my.ser.ver.ip/
[Sun Feb 05 23:43:24.645320 2017] [core:debug] [pid 3318] core.c(3525): [client my.ho.me.ip:port] AH00122: redirected from r->uri = /home/ebot/ebot-web/web/index.php, referer: http://my.ser.ver.ip/
[Sun Feb 05 23:43:24.645473 2017] [core:debug] [pid 3318] core.c(3525): [client my.ho.me.ip:port] AH00122: redirected from r->uri = /stats, referer: http://my.ser.ver.ip/`

I followed the ebot part of this setup to the letter http://robertan.com/home/2016/09/03/setting-up-csgo-dedicated-server-with-ebot/

**Comment by MikkelDK** [comment]
.htaccess needed to be copyed (it under: /home/ebot/ebot-web/web/ >> .htaccess is there (try check about it is created.)

**Comment by dumle29** [comment]
Tried again following this guide here: http://forum.esport-tools.net/d/2-how-to-install-ebot-on-debian-ubuntu-for-beginners

Still got error 500 on any links, but this time apaches error log gave me something to work with, and the problem was that the files in the cache that it needed were not of the right permission.  I ran 
`chmod -R 777 cache` and that fixed it

**Comment by MikkelDK** [comment]
if there is no problem anymore. will i recommend you to "close" the issue :)

**Comment by dumle29** [comment]
makes sense :)
