### ISSUE TITLE
ebot is recognizing commands like !ready?

### ISSUE THREAD

**Issue by SwifterGames** [deStrO/eBot-CSGO-Web#91]
I dont know why it isnt working can someone help please?
The Ip is:
connect robert.dathost.net:28244

**Comment by SeatloN** [comment]
Don't use that dns string, use the public ip that console is giving you ex.000.000.000.000 in you case it should be something like 104.128.62.34

**Comment by 0BuRner** [comment]
Why not using dns adress?

**Comment by SeatloN** [comment]
It does not work =) 

http://dathost.net/blog/how-to-add-e-bot-to-your-dathost-net-or-other-dedicated-server/

**Comment by MikkelDK** [comment]
Are you sure, you have tryed and type the "Public IP" in? I'm hosting own ebot sites. and dathost works fine there. :)
