### ISSUE TITLE
PROBLEMS WHEN ACCESSING THE EBOT WEB PAGE

### ISSUE THREAD

**Issue by j4p0n** [deStrO/eBot-CSGO-Web#96]
I'm having trouble trying to access the eBot webpage because it always displays the following error:
-----------------
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster @ localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.18 (Ubuntu) Server at 192.168.0.101 Port 80

---------------------

This is the apache error log (/var/log/apache2/error.log)
-

[Sat Oct 28 16: 54: 41.564030 2017] [http: error] [pid 18320] [client 192.168.0.101:35346] AH02428: Empty response header name, aborting request

-----------

How do I fix the problem for the web page to display?

**Comment by digimon-dk** [comment]
Install PHP 5 

mkdir /home/install
cd /home/install
wget http://be2.php.net/get/php-5.5.15.tar.bz2/from/this/mirror -O php-5.5.15.tar.bz2
tar -xjvf php-5.5.15.tar.bz2
cd php-5.5.15
./configure --prefix /usr/local --with-mysql --enable-maintainer-zts --enable-sockets --with-openssl --with-pdo-mysql
make
make install
cd /home/install
wget http://pecl.php.net/get/pthreads-2.0.7.tgz
tar -xvzf pthreads-2.0.7.tgz
cd pthreads-2.0.7
/usr/local/bin/phpize
./configure
make
make install
echo 'date.timezone = Europe/Paris' >> /usr/local/lib/php.ini
echo 'extension=pthreads.so' >> /usr/local/lib/php.ini
